version: '3.5'

services:
  rpg_bot_db:
    container_name: rpg_bot_cont
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    image: postgres:14.3-alpine
    volumes:
      - rpg_bot_data:/var/lib/postgresql/data  

  rpg_test_db:
    container_name: rpg_test_cont
    ports:
      - ${DB_PORT_test}:5432
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    image: postgres:14.3-alpine
    volumes:
      - rpg_test_data:/var/lib/postgresql/data  
  
volumes:
  rpg_bot_data:
  rpg_test_data: