"""Map

Revision ID: 9af4f106afd9
Revises: 3aadfda97ccf
Create Date: 2025-01-22 21:27:35.646828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af4f106afd9'
down_revision: Union[str, None] = '3aadfda97ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_table',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('tile_name', sa.String(), nullable=False),
    sa.Column('hero_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['hero_table.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index('_x_y_idx', 'map_table', ['x', 'y'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('_x_y_idx', table_name='map_table')
    op.drop_table('map_table')
    # ### end Alembic commands ###
