"""Создание Hero

Revision ID: 3aadfda97ccf
Revises: 2ae0c47911ac
Create Date: 2025-01-19 13:54:10.058923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aadfda97ccf'
down_revision: Union[str, None] = '2ae0c47911ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_table',
    sa.Column('pk', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('avatar_file_in_tg_id', sa.String(length=256), nullable=False),
    sa.Column('nickname', sa.String(length=25), nullable=False),
    sa.Column('energy', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user_table.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero_table')
    # ### end Alembic commands ###
